import "./globals.css";
import IconNavbar from "./components/nav";
import StarParticles from "./particles/starbg";
import CursorSpotlight from "./components/cursor-spotlight";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ boxSizing: "border-box", fontFamily: "Arial, Helvetica, sans-serif" }}>
        <StarParticles />
        <CursorSpotlight />
        <IconNavbar />
        {children}
      </body>
    </html>
  );
}
